FORMAT: 1A

# testapi
Notes API is a *Thing* service similar to a physical space where things can be.

# Group Things
Thing related resources of the **Things API**

## Things [/things]
### List all Things [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "thing 1"
        }, {
          "id": 2, "name": "thing 2"
        }]

### Create a Thing [POST]
+ Request (application/json)

        { "name": "meeple" }

+ Response 201 (application/json)

        { "id": 3, "name": "meeple" }

## Note [/things/{id}]
A Thing with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Thing to do stuff with

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "thing 2" }

### Remove a Thing [DELETE]
+ Response 204
